# Generated by Django 4.1.7 on 2023-04-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Topic_name',
            new_name='topic_name',
        ),
        migrations.RenameField(
            model_name='webpage',
            old_name='Topic_name',
            new_name='topic_name',
        ),
    ]
